#+TITLE: Theming of Open edX Platform
#+Author: VLEAD
#+Date: [2016-10-17 Monday]

* Introduction
This document briefly explaines the process of customizing theme in
openedx.

* Requirements 
  High level requirement is to make Virtual Labs Open edX, look
  similiar to the [[http://landingpage.base1.vlabs.ac.in/][Virtual labs website]] before transition.  Following
  are the individual requirements -

** Virtual Labs landing page requirements   
  + Virtual Labs logo with a common header is to be there on every
    screen of website.
  + Register/Login button as provided by Open edX.
  + Virtual Labs banner with other =About Virtual Labs= images on
    slider.
  + =Number of Labs=, =Experiments=, =Usage= counts and =Workshop
    Usage= to be displayed on landing page.
  + Usage must be dynamically fetched from Analytics server.
  + =Disciplines and Domains= section with tile list of all the
    available disciplines as they were in landingpage.vlabs.ac.in.
  + Each discipline in =Disciplines and Domains= section must open the
    list of labs in of corresponding disciplines.
  + A marquee banner of all =Participating Institutes= having coloured
    logo of each institute.
  + Click on each logo must open a web page listing labs of that
    institute.
  + A =Menu item= with following items in the menu -
    - =All Labs= to open =Electronics and Communications= page.
    - =All labs on Open edX= to open /courses api of Open edX.
    - =Teachers' Community= to open G+ Teachers' community page.
    - =Workshops= to open Virtual Labs workshops page.
    - =College Cloud Edition= to open College Cloud Edition page.
    - =Contact= to open contact us page.
    - =FAQ= to open FAQ page.


  + A common footer with following sections -
    - =First Section - UPDATES= (Lab Integration Kit Releases, First Integration
      Workshop at IIIT Hyderabad, Summer Integration Workshop at IIT
      Guwahati, QA Integration Workshop at IIIT Hyderabad, A new set
      of 25 Virtual Labs on Portable Media).
    - Second section with =Contact us=, =Feedback=, =Licensing=, =Teachers' Community=,
      =Lab Assessment Form=, =College Cloud Edition=, =Expression of
      Interest for Workshop=.
    - Third section with =FAQ=, =Community=, =Nodal Centers=, =Sakshat
      Portal=, =Outreach Portal=, =Announcements=, =Labs Developed by
      Nodal Centers=.
    - Fouth section with logos and links of social networking sites of
      Virtual Labs (Facebook, Twitter, LinkedIn, Youtube)
    - A logo of Open edX which following the [[https://open.edx.org/sites/default/files/wysiwyg/Open%20edX%20and%20Powered%20by%20Open%20edX%20Visual%20ID%20Guidelines.pdf][Visual Guidelines]] mentioned by
      Open edX community.
    
    
** Virtual Labs custom pages requirements 
   Custom pages are served to meet the requirement of similiarty to
   the existing landingpage.vlabs.ac.in.
*** Requirements for FAQ page
   
    + FAQ section for =Expression of Interest for Workshops=.
    + FAQ section for =Virtual LAbs College Cloud Edition=.
    + FAQ section for =Virtual Labs=.

*** Requirements for Virtual Labs Workshops page 
    A custom web page with common header, footer to pile up
    information about workshops.

*** Requirements for College Cloud Edition page
    A custome web page with common header, footer to pile up
    information on College Cloud Edition.
 
*** Requirements for Discipline and Domains page
    This page must be similiar to the one in [[http://landingpage.vlabs.ac.in][Virtual Labs website]]
    before transition.
    + A custom web page for each discipline, listing labs falling into it.
    + Labs on Open edX must have a =*= symbol.
    + Labs not on Open edX sould not have any symbol.
    + Sections for =Reference Books=, =Syllabus Mapping=, =Lecture=
      wherever available.
  
*** Requirements for Participating Institutes page 
    This page must be similiar to the one in [[http://landingpage.vlabs.ac.in][Virtual Labs website]]
    before transition.
    + A custom web page for each institute, listing labs falling into it.
    + Labs on Open edX must have a =*= symbol.
    + Labs not on Open edX sould not have any symbol.
    + Sections for =Reference Books=, =Syllabus Mapping=, =Lecture=
      wherever available.
 
*** Requirements Licensing page 
    This page must be similiar to the one in [[http://landingpage.vlabs.ac.in][Virtual Labs website]]
    before transition -
    + Mention =Virtual Labs Content Licensing=
    + Mention =Virtual Labs Software Licensing=




  

* Install 

ation of theme
  To apply comprehensive theme on dogwood follow the steps -
  + Login to edX server 
  + cd /edx/app/edxapp/themes/
  + Clone repository https://github.com/openedx-vlead/vlabs-edx-bootstrap-theme
    #+BEGIN_SRC command
    git clone https://github.com/openedx-vlead/vlabs-edx-bootstrap-theme edx-bootstrap-theme
    #+END_SRC
  + Give proper permissions 
  + Open /edx/app/edxapp/lms.env.json
  + Change the following keys -
    #+BEGIN_SRC command
    "COMPREHENSIVE_THEME_DIRS": ["/edx/app/edxapp/themes"]
    "ENABLE_COMPREHENSIVE_THEMING": true
    "DEFAULT_SITE_THEME": "edx-bootstrap-theme"
    "USE_CUSTOM_THEME": false
    "THEME_NAME": ""
    #+END_SRC
  + Save changes
  + Compile changes using the commands below -
    #+BEGIN_SRC command
    sudo -H -u edxapp bash 
    cd /edx/app/edxapp/edx-platform
    source ../edxapp_env
    paver update_assets lms --setting=aws
   #+END_SRC
  + Once done, restart services using /edx/bin/supervisorctl/ restart all 


* Enable external custom features in VLABS Open edX
  All Labs available must be categorized as that in vlabs.ac.in on the basis of 
  Disciplines and Institutes. To acheive this, custom html pages are served
  from VLABS Open edX server. Following features are server from custom html  -

  + Search Feature 
  + Analytics 
  + Announcements 
  + Contact Us 
  + FAQ
  
 To apply the changes, follow the steps given below -
  
  + Clone repository https://github.com/openedx-vlead/vlabs-edx-bootstrap-theme
    #+BEGIN_SRC command
    git clone https://github.com/openedx-vlead/vlabs-edx-bootstrap-theme edx-bootstrap-theme
    #+END_SRC

  + Change directory to scripts in vlabs-edx-bootstrap-theme 
    #+BEGIN_SRC command
    cd edx-bootstrap-theme/scripts 
    #+END_SRC

  + Execute the shell script 
    #+BEGIN_SRC command
    sh set-features.sh 
    #+END_SRC
   
  + Compile the assets of theme 
  
