#+TITLE: Theming of Open edX Platform
#+Author: VLEAD
#+Date: [2016-10-17 Monday]

* Introduction
This document briefly explaines the process of customizing theme in
openedx.


* [[./requirements/index.org][Requirements]]

* Installation of theme

  To apply comprehensive theme on dogwood follow the steps -
  + Login to edX server 
  + cd /edx/app/edxapp/themes/
  + Clone repository https://github.com/openedx-vlead/vlabs-edx-bootstrap-theme
    #+BEGIN_SRC command
    git clone https://github.com/openedx-vlead/vlabs-edx-bootstrap-theme edx-bootstrap-theme
    #+END_SRC
  + Give proper permissions 
  + Open /edx/app/edxapp/lms.env.json
  + Change the following keys -
    #+BEGIN_SRC command
    "COMPREHENSIVE_THEME_DIRS": ["/edx/app/edxapp/themes"]
    "ENABLE_COMPREHENSIVE_THEMING": true
    "DEFAULT_SITE_THEME": "edx-bootstrap-theme"
    "USE_CUSTOM_THEME": false
    "THEME_NAME": ""
    #+END_SRC
  + Save changes
  + Compile changes using the commands below -
    #+BEGIN_SRC command
    sudo -H -u edxapp bash 
    cd /edx/app/edxapp/edx-platform
    source ../edxapp_env
    paver update_assets lms --setting=aws
   #+END_SRC
  + Once done, restart services using /edx/bin/supervisorctl/ restart all 



* Process to make a release ?
** Configuring the instance 
  + Create an AMI from the existing production instance of
    https://vlabs.ac.in .
  + Launch a machine out of the AMI.
  + Apply your changes and test it throughly.
  + Once tested properly, stop the production instance and assign the
    elastic ip to the new instance.
  
** Writing the release notes
   + Write proper release notes as given in [[https://github.com/openedx-vlead/vlabs-edx-bootstrap-theme/blob/master/release-notes/vlabs-edx-theme-v1.0.0.org][sample]].
   
** Make a github release 
   + Make a release as given [[https://github.com/openedx-vlead/vlabs-edx-bootstrap-theme/releases][here]]

** Write a release email 
   Write the email as shown below in the sample -
   #+BEGIN_SRC command
   Release : VLABS Open edX v2.0.0
   Ashay Maheshwari <ashay@vlabs.ac.in>	Wed, Feb 22, 2017 at 9:12 PM
   To: vlead-staff <vlead-staff@vlabs.ac.in>, announce@vlabs.ac.in
   Hello Team,

   This is to inform about the release of VLABS Open edX v2.0.0
   Release note are available here - https://github.com/openedx-vlead/vlabs-edx-bootstrap-theme/releases/tag/v2.0.0   
   #+END_SRC 

   
